version: "3.8"
services:
  gemini-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "8787:8787"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8787/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    # OPCIONAL: si quieres persistir solo el estado local de Miniflare
    # volumes:
    #   - gemini_data:/app/.mf
# volumes:
#   gemini_data:
#     driver: local
